### ISSUE TITLE
Change project --> wrapped C/C++ object of type QgsVectorLayer has been deleted

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-api-qgis-client#155]
**Topdesk 2104 0118 Leendert**

* threedi-api-qgis-client version: 2.4.0 (QGIS 3.16.5) 
* Python version: 3.7.0
* Operating System: Windows

### Description

If you have a model loaded via the API QGIS plugin, and change the project (via QGIS main menu project --> New),  the model disappears and you get a new page.  However, if you then want to log out or load in another model via the API QGIS plugin, you get the following error

### Error

```
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_api_qgis_client\widgets\log_in.py", line 206, in load_model
    self.unload_cached_layers()
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_api_qgis_client\widgets\log_in.py", line 196, in unload_cached_layers
    QgsProject.instance().removeMapLayer(self.cells_layer)
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\PyJWT-1.7.1-py2.py3-none-any.whl
C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl
```

### Expected result
I do not know how often this occurs, but when it does happen, you are stuck. QGIS has to be restarted. 
So, I would like one of the following:

1. Be logged out after changing project (preferably with a warning) 
2. Something with an if, else statement: if cells present, remove cells in project ; else, ...   (if that is indeed the issue)

**Comment by lisannewapstra** [comment]
I prefer the 2nd option.
@Jonasvsl  what do you think? and is this something for @reinout ?

**Comment by Jonasvsl** [comment]
I haven't seen this before. but to me it seems that the 1st one is most logical. I don't understand how the 2nd one is going to solve this problem

**Comment by leendertvanwolfswinkel** [comment]
Duplicate: #353
