### ISSUE TITLE
Lateral csv upload gives not helpful error back ('string indices must be integers') 

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-api-qgis-client#157]
* threedi-api-qgis-client version: 2.4.1
* Python version:  3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
* Operating System: Windows

### Description

When uploading a csv with laterals that contain a connection_node_id that is not present in the model, it gives an unrelated/unclear error back.
You'd expect the error: "the connecton_node_id in the csv file is not present in your model", or something like that. 

### How to reproduce

file.csv
```
_id,connection_node_id,timeseries
"1","22034723847","0,0
999999,0"_
```
In API client connect to any model (22034723847 being an id that is not likely present in any model). 
Go to simulate --> New --> include laterals --> Next --> choose name, Next--> choose 1 hour or so, Next > Upload csv and leave current settings --> Add to queue

### Error message
```
An error has occurred while executing Python code:
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\clean/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 1758, in run_new_simulation
    raise e
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\clean/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 1753, in run_new_simulation
    tc.make_action_on_simulation(sim_id, name="start")
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\clean/python/plugins\threedi_api_qgis_client\api_calls\threedi_calls.py", line 137, in make_action_on_simulation
    action = api.simulations_actions_create(str(simulation_pk), action_data)
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\api\simulations_api.py", line 64, in simulations_actions_create
    return self.simulations_actions_create_with_http_info(simulation_pk, data, **kwargs)  # noqa: E501
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\api\simulations_api.py", line 165, in simulations_actions_create_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\api_client.py", line 370, in call_api
    _preload_content, _request_timeout, _host)
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\api_client.py", line 189, in __call_api
    raise e
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\api_client.py", line 186, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\api_client.py", line 414, in request
    body=body)
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\rest.py", line 272, in POST
    body=body)
  File "C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl\openapi_client\rest.py", line 225, in request
    raise ApiException(http_resp=r)
openapi_client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'server': 'openresty/1.15.8.3', 'date': 'Fri, 04 Jun 2021 12:25:49 GMT', 'content-type': 'application/json', 'content-length': '653', 'vary': 'Accept, Origin, Cookie', 'allow': 'POST, OPTIONS', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=63072000', 'referrer-policy': 'strict-origin-when-cross-origin', 'x-xss-protection': '1'})
HTTP response body: {"errors":[{"instance":{"url":"https://api.3di.live/v3.0/files/145597/","storage_name":"MINIO_DEV","filename":"test_leteral_5_laterals.json","bucket":"3di","prefix":"None","etag":"be9eb12a12fc2557084174a6f3806436","size":"143","expiry_date":"2021-06-12","related_object":"https://api.3di.live/v3.0/simulations/25092/events/lateral/file/1501/","type":"bulklateral","state":"error","state_description":"Invalid file, see related event for further details","meta":"None","id":"145597"},"reason":"File processing error: Invalid file, see related event for further details","resolution":"Fix the error, remove the event (see related_object) and try again"}]}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\clean/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 1767, in run_new_simulation
    error_details = error_body["details"] if "details" in error_body else error_body
TypeError: string indices must be integers
Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1ed6
Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\clean/python
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\clean/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\clean/python
.
C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\PyJWT-1.7.1-py2.py3-none-any.whl
C:\Users\lisanne.wapstra\AppData\Roaming\QGIS\QGIS3\profiles\clean\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.23-py2.py3-none-any.whl
```

@Jonasvsl

**Comment by ldebek** [comment]
More detailed error message (reason and related event object) and re is now taken from API exception body if available.
