### ISSUE TITLE
Revision does not exist error when trying to upload

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#302]
How to reproduce:

- Load schematisation "prinseneiland v3", revision 1
- UPLOAD > New Upload

```
threedi_api_client.openapi.exceptions.ApiException: (404) Reason: Not Found HTTP response headers: HTTPHeaderDict({'server': 'openresty/1.15.8.3', 'date': 'Sun, 23 Jan 2022 22:04:51 GMT', 'content-type': 'application/json', 'content-length': '36', 'vary': 'Accept, Origin, Cookie', 'allow': 'GET, HEAD, OPTIONS', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'strict-transport-security': 'max-age=63072000', 'referrer-policy': 'strict-origin-when-cross-origin', 'x-xss-protection': '1'}) HTTP response body: {"detail":"Revision does not exist"} 
Traceback (most recent call last):
  File "C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_api_qgis_client\widgets\upload_status.py", line 105, in upload_new_model
    if current_wip_revision.number > 0
  File "C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_api_qgis_client\api_calls\threedi_calls.py", line 619, in fetch_schematisation_latest_revision
    schematisation_revision = self.threedi_api.schematisations_latest_revision(schematisation_pk)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\api\v3_beta_api.py", line 291, in schematisations_latest_revision
    return self.schematisations_latest_revision_with_http_info(id, **kwargs)  # noqa: E501
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\api\v3_beta_api.py", line 380, in schematisations_latest_revision_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\api_client.py", line 370, in call_api
    _preload_content, _request_timeout, _host)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\api_client.py", line 189, in __call_api
    raise e
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\api_client.py", line 186, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\api_client.py", line 394, in request
    headers=headers)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\rest.py", line 235, in GET
    query_params=query_params)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl\threedi_api_client\openapi\rest.py", line 225, in request
    raise ApiException(http_resp=r)
threedi_api_client.openapi.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'server': 'openresty/1.15.8.3', 'date': 'Sun, 23 Jan 2022 22:04:51 GMT', 'content-type': 'application/json', 'content-length': '36', 'vary': 'Accept, Origin, Cookie', 'allow': 'GET, HEAD, OPTIONS', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'strict-transport-security': 'max-age=63072000', 'referrer-policy': 'strict-origin-when-cross-origin', 'x-xss-protection': '1'})
HTTP response body: {"detail":"Revision does not exist"}
```

**Comment by leendertvanwolfswinkel** [comment]
Probably messed up the repository due to another bug that has been fixed by now
