### ISSUE TITLE
Simulation status not updating 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#33]
* threedi-api-qgis-client version:
0.4.2
* Python version:

* Operating System:

### Description

All simulations that are started are not going past 'starting up simulation', whereas in reality they are running. 

![image](https://user-images.githubusercontent.com/1453159/78987890-9f07f680-7b2f-11ea-8ed7-008bb384fe1f.png)

### What I Did
I started a simulation using the new simulation option in the plugin.

Error messages in QGIS

2020-04-10T11:33:47     WARNING    Traceback (most recent call last):
              File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\simulation_overview.py", line 168, in run
              self.progresses = tc.all_simulations_progress(self.simulations_list)
              File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\api_calls\threedi_calls.py", line 84, in all_simulations_progress
              sim_progress = Progress(percentage=0, time=status_time)
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\QGIS\QGIS3\profiles\qgis310\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0b10-py2.py3-none-any.whl\openapi_client\models\progress.py", line 56, in __init__
              self.time = time
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\QGIS\QGIS3\profiles\qgis310\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0b10-py2.py3-none-any.whl\openapi_client\models\progress.py", line 78, in time
              raise ValueError("Invalid value for `time`, must not be `None`") # noqa: E501
             ValueError: Invalid value for `time`, must not be `None`
             
###Possible solutions
- update the openapi client used in this plugin
- Apparently in the code time can be None, this should be set to 0 or something similar I think

**Comment by DamnBack** [comment]
Fixed.
