### ISSUE TITLE
log in problems?

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#35]
* threedi-api-qgis-client version: 0.4.3
* Python version:
* Operating System:

### Description

I wanted to log in

### What I Did

After logging in, I pressed the 'simulate' button. Then I got a python error:

2020-04-14T15:24:35     WARNING    Traceback (most recent call last):
              File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\threedi_api_qgis_client_dockwidget.py", line 101, in show_simulate_overview
              self.organisation = self.log_in_dlg.organisations[repository.organisation]
             KeyError: '61f5a464c35044c19bc7d4b42d7f58cb'
```

After ignoring the error/warning and continuuing to start up a simulation I can follow the whole menu. After pressing 'start simulation' I get the following traceback:

An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'unique_id' 
Traceback (most recent call last):
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 588, in run_new_simulation
    organisation_uuid = self.parent_dock.organisation.unique_id
AttributeError: 'NoneType' object has no attribute 'unique_id'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.9-Madeira Madeira, 54585165bb 

Python Path:
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python
C:\Users\jonas.vanschrojenste\AppData\Roaming\QGIS\QGIS3\profiles\qgis310\python\plugins\threedi_api_qgis_client\deps\PyJWT-1.7.1-py2.py3-none-any.whl
C:\Users\jonas.vanschrojenste\AppData\Roaming\QGIS\QGIS3\profiles\qgis310\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0b16-py2.py3-none-any.whl
```

**Comment by DamnBack** [comment]
Hi @Jonasvsl Could you please check if issue occurs on plugin version 0.4.4?

**Comment by DamnBack** [comment]
Fixed.
