### ISSUE TITLE
Compatibility with schema 217

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#462]
- [ ]  Set minimum schema version to 217
- [ ]  Upgrade the spatialite that is shipped with the plugin to schema version 217

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I tested uploading the data for a schematisation that has both vegetation and interflow rasters. I get the error below. Schematisation data: https://we.tl/t-PAeG9hCpKf

```
An error has occurred while executing Python code: 

AttributeError: 'SelectFilesWidget' object has no attribute 'widget_interflow' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_models_and_simulations\widgets\upload_overview.py", line 162, in upload_new_model
    upload_wizard_dialog = UploadWizard(self.plugin_dock, self)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_models_and_simulations\widgets\upload_wizard.py", line 622, in __init__
    self.select_files_page = SelectFilesPage(self)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_models_and_simulations\widgets\upload_wizard.py", line 592, in __init__
    self.main_widget = SelectFilesWidget(self)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_models_and_simulations\widgets\upload_wizard.py", line 238, in __init__
    self.initialize_widgets()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\threedi_models_and_simulations\widgets\upload_wizard.py", line 363, in initialize_widgets
    self.widget_interflow,
AttributeError: 'SelectFilesWidget' object has no attribute 'widget_interflow'
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Error above should be fixed now.
