### ISSUE TITLE
Python error when logging out

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#525]
How to reproduce: 

- Log in
- Log out

```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'unload_cached_layers' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_models_and_simulations\widgets\threedi_dockwidget.py", line 77, in on_log_in_log_out
    self.on_log_out()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_models_and_simulations\widgets\threedi_dockwidget.py", line 96, in on_log_out
    self.simulation_overview_dlg.model_selection_dlg.unload_cached_layers()
AttributeError: 'NoneType' object has no attribute 'unload_cached_layers'
```

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt tested, please merge
