### ISSUE TITLE
Simulation Wizard: 3Di simulaties met 2D lateraal aanzetten niet meer mogelijk in Modeller Interface 2406 0047

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#576]
For example, when trying to start the simulation wizard with this 3Di model, the error below occurs

https://management.3di.live/schematisations/8548/57516?organisation=87b8d584124849259dc26854de8cd1e5

Org: Demo Imagem

```
An error has occurred while executing Python code:
AttributeError: 'SimulationWizard' object has no attribute 'substances_page'
Traceback (most recent call last):
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_models_and_simulations\widgets\simulation_overview.py", line 159, in new_wizard_init
self.new_simulation(simulation, settings_overview, events, lizard_post_processing_overview)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_models_and_simulations\widgets\simulation_overview.py", line 185, in new_simulation
self.simulation_wizard = SimulationWizard(
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_models_and_simulations\widgets\simulation_wizard.py", line 2634, in __init__
self.laterals_page = LateralsPage(self)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_models_and_simulations\widgets\simulation_wizard.py", line 2468, in __init__
self.main_widget = LateralsWidget(self)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_models_and_simulations\widgets\simulation_wizard.py", line 655, in __init__
self.substances = parent_page.parent_wizard.substances_page.main_widget.substances
AttributeError: 'SimulationWizard' object has no attribute 'substances_page'
```

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel I run into this issue too and fixed it together with the boundary condition page in this PR: https://github.com/nens/threedi-api-qgis-client/pull/559
