### ISSUE TITLE
choosing a model to include breaches which doesn't have breaches causes a crash

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#79]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description
when I choose breaches in a model that doesn't have them
![image](https://user-images.githubusercontent.com/1453159/85296409-a3db1600-b4a1-11ea-8ff5-cfa9a8b46d82.png)

I get this message:
An error has occurred while executing Python code: 

ValueError: invalid literal for int() with base 10: '' 
Traceback (most recent call last):
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\simulation_overview.py", line 95, in new_wizard_init
    self.new_simulation(int_conditions)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\simulation_overview.py", line 99, in new_simulation
    self.simulation_wizard = SimulationWizard(self.parent_dock, init_conditions)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 994, in __init__
    self.breaches_page = BreachesPage(self, initial_conditions=init_conditions)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 956, in __init__
    self.main_widget = BreachesWidget(self, initial_conditions=initial_conditions)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 769, in __init__
    self.fill_comboboxes()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 777, in fill_comboboxes
    self.write_values_into_dict()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\qgis310/python/plugins\threedi_api_qgis_client\widgets\wizard.py", line 786, in write_values_into_dict
    "breach": self.breaches.get(int(breach_id)),
ValueError: invalid literal for int() with base 10: ''

prefereed : not a crash but a gentle message that breaches are not available. let me know if backend work is required for his

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Should be fixed now.
